### ISSUE TITLE
Initial Inject API Endpoint

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-injector#1]
An API endpoint should be developed to: 
- [x] be reachable from `/api/inject`
- [x] accept 2 team `id`s as query parameters `/api/inject?team1=34&team2=9`
- [x] give a `400 Bad Request` error if not given 2 teams
- [x] create a new row in the `game` table
- [x] create new rows in the `team_game` table for each team (this connects the team and the game)
- [x] report any error as a `400 Bad Request`
- [x] if successful, report `200 OK`

**Comment by CoderOfTheLight** [comment]
Testing stages started.

**Comment by russleyshaw** [comment]
Good
