### ISSUE TITLE
[discuss] Preventing abuse of competitor facing injector service.

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-injector#3]
How will we prevent someone from clicking the "fight" button 1000s of times, yet still be able to service everyone?

**Comment by russleyshaw** [comment]
I don't believe we'd be able to identify based on IP address because all the competitors would have the same IP since we are all on the same local network. 

@LoneGalaxy brought up a cooldown timer

This could possibly be done by setting a cookie when the button is clicked and forcing them to wait until X seconds have elapsed until they can click again.

**Comment by JacobFischer** [comment]
While that would be a good idea, if you want better security bear in mind a malicious entity could bypass that with ease, or just a curious student (of which we have plenty).

I think something like a _serverside_ cooldown timer would be ideal. For example, we make it so any team can only have up to like 5 queued injector games, and no matter how many more requests they send they can't get more server side. In that manner I wouldn't even do the client side cool down.

**Comment by russleyshaw** [comment]
The issue is there is no authentication right now. Anyone can go to the injector page. 

I think it might be too much overhead to introduce team authentication?

**Comment by MatthewQualls** [comment]
What if a team can't be queued into more than ten injector games?

**Comment by JacobFischer** [comment]
Why not just piggyback off the auth the front end of the competitor website uses?

**Comment by russleyshaw** [comment]
@MatthewQualls someone could prevent a team from playing by queuing them against shell AI. Aka. Sabotage.

@JacobFischer maybe, but currently we were working towards the direction of the API to only allow trusted users (aka a colisee user and a web user). our colisee-api is not front facing for competitors yet. 

I would not want to rely on whatever authentication Ophelia implements because that would create too much of a dependency on their implementation details.

**Comment by russleyshaw** [comment]
Adding basic OAuth through GitLab as per #4
